# Generated by Django 5.1.6 on 2025-02-20 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_tache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='tache',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tache',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.projet'),
        ),
        migrations.AlterField(
            model_name='tache',
            name='statut',
            field=models.CharField(choices=[('A faire', 'À faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='A faire', max_length=10),
        ),
    ]
